### ISSUE TITLE
Add support to use Common Name (CN) as DN attribute for user entry

### ISSUE THREAD

**Issue by hlavki** [hlavki/g-suite-identity-sync#53]
According to issue #10 add support to set CN as user dn attribute.

**Comment by hlavki** [comment]
@dimasdjs, I don't know if I understand your problem. I created patch that creates user entry with DN: `cn=Michal Hlaváč,ou=people,dc=hlavki,dc=eu` like this:

Attr | Value
-- | --
objectClass | inetOrgPerson (structural)
uid | miso@hlavki.eu
cn | Michal Hlaváč
sn | Hlaváč
employeeNumber | 10071526xxxxxxx636
employeeType | INTERNAL
givenName | Michal
mail | miso@hlavki.eu

Is that what you need?

**Comment by dimasdjs** [comment]
thank you for your respond sir. sorry for my late respond
@hlavki  `cn=Michal Hlaváč,ou=people,dc=hlavki,dc=eu` , this is the format i need sir, without uid , because samba active directory doesnt support with uid.

**Comment by hlavki** [comment]
thanks @dimasdjs, but does samba support `uid` attribute?

**Comment by dimasdjs** [comment]
no sir, i've tried a couple times to add `uid` attribute when adding user in samba, but it doesnt work. 
and then i see attribute user that created in samba there is no `uid` attribute sir @hlavki

**Comment by lesmono** [comment]
Hi guys, related to this https://wiki.samba.org/index.php/Samba_&_LDAP
I suggest to use LDAP_USER_ATTR_DEFAULT = "cn"; rather than "uid", but you still need to supply "uid" as mandatory attribute.

**Comment by hlavki** [comment]
Thanks @lesmono, this is exactly what I needed to know. LDAP_USER_ATTR_DEFAULT remains `uid` because of backward compatibility, but will easy to configure.

**Comment by hlavki** [comment]
this issue should be fixed in master branch, but I cannot test it. Would by great if anobody with samba could test it. To use cn as user attribute you can run:
```bash
docker-compose exec identity /opt/karaf/bin/client \
    'config:edit eu.hlavki.identity.ldap; config:property-set ldap.users.dnAttr cn; config:update'
```

**Comment by lesmono** [comment]
Ok, will update soon about the status of this new code update.
Thanks in advance.

**Comment by dimasdjs** [comment]
hello sir @hlavki 

thank you for your update.
ive tried use your updated image, but i still get same error.

here is my docker-compose.yml:

```
version: "3"

services:
  identity:
    image: hlavki/g-suite-identity-sync:0.4.7
    ports:
      - 8181:8181
      - 8101:8101
    environment:
      - LDAP_HOST=admin.example.org
      - SLAPD_BIND_DN=cn=admin,dc=example,dc=org
      - SLAPD_BASE_DN=dc=example,dc=org
      - SLAPD_PASSWORD=changeme
      - GSUITE_DOMAIN=example.org
      - GSUITE_CLIENT_ID=*******.apps.googleusercontent.com
      - GSUITE_CLIENT_SECRET=******
    volumes:
      - identity-config:/opt/karaf/etc/identity
volumes:
  identity-config:

```

i didnt create ldap image because i already had one.

and here is the screenshoot of error message:

![image](https://user-images.githubusercontent.com/31427476/73329111-e7cd4480-428e-11ea-81fb-e6318142d74a.png)

I hope it can help you sir. 

Thank you before.
