### ISSUE TITLE
Get a "No service was found" message when clicking on the Sign in button

### ISSUE THREAD

**Issue by rsaple** [hlavki/g-suite-identity-sync#9]
Here's the thing. I have created a trial GSuite account just for testing this particular utility. Did the pre-install gsuite- configuration as described without any issue. Edited the docker-compose.yml to reflect our ldap setup. Ran the docker commands successfully. I can access the homepage on localhost:8181. But when I click on the sign in button I get a terse message saying "No service was found". 

Docker trace also throws some errors
```
identity_1  | 	at org.apache.felix.framework.FrameworkStartLevelImpl.run(FrameworkStartLevelImpl.java:308) [?:?]
identity_1  | 	at java.lang.Thread.run(Thread.java:748) [?:?]
identity_1  | Caused by: org.osgi.service.blueprint.container.ComponentDefinitionException: Error when instantiating bean ldapConnection of class com.unboundid.ldap.sdk.LDAPConnection
identity_1  | 	at org.apache.aries.blueprint.container.BeanRecipe.wrapAsCompDefEx(BeanRecipe.java:361) ~[?:?]
identity_1  | 	at org.apache.aries.blueprint.container.BeanRecipe.getInstanceFromType(BeanRecipe.java:351) ~[?:?]



2018-06-14T08:46:02,328 | INFO  | features-1-thread-1 | FeaturesServiceImpl              | 10 - org.apache.karaf.features.core - 4.1.5 | Done.
identity_1  | 2018-06-14T08:46:02,330 | INFO  | paxweb-extender-2-thread-1 | HttpServiceContext               | 152 - org.ops4j.pax.web.pax-web-jetty - 6.0.9 | registering JasperInitializer
identity_1  | 2018-06-14T08:46:02,678 | INFO  | paxweb-extender-2-thread-1 | ContextHandler                   | 125 - org.eclipse.jetty.util - 9.3.21.v20170918 | Started HttpServiceContext{httpContext=WebAppHttpContext{eu.hlavki.identity.g-suite-identity-sync-web - 20}}
identity_1  | 2018-06-14T08:51:00,530 | ERROR | Blueprint Extender: 2 | BlueprintContainerImpl           | 32 - org.apache.aries.blueprint.core - 1.8.3 | Unable to start blueprint container for bundle eu.hlavki.identity.g-suite-identity-sync-services/0.3.1 due to unresolved dependencies [(objectClass=eu.hlavki.identity.services.ldap.LdapAccountService)]
identity_1  | java.util.concurrent.TimeoutException: null
identity_1  | 	at org.apache.aries.blueprint.container.BlueprintContainerImpl$1.run(BlueprintContainerImpl.java:370) [32:org.apache.aries.blueprint.core:1.8.3]
identity_1  | 	at org.apache.aries.blueprint.utils.threading.impl.DiscardableRunnable.run(DiscardableRunnable.java:48) [32:org.apache.aries.blueprint.core:1.8.3]
identity_1  | 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:?]
identity_1  | 	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:?]

identity_1  | 2018-06-14T12:23:11,751 | WARN  | qtp1957879929-71 | ServletController                | 54 - org.apache.cxf.cxf-rt-transports-http - 3.2.2 | Can't find the request for http://localhost:8181/cxf/identity/user's Observer 
identity_1  | 2018-06-14T12:29:00,793 | WARN  | qtp1957879929-72 | ServletController                | 54 - org.apache.cxf.cxf-rt-transports-http - 3.2.2 | Can't find the request for http://localhost:8181/cxf/oidc/rp's Observer 

```

I guess the issue is with the docker-compose.yml file but I'm not sure. Being a docker noob complicates things further. Can someone help me through this? Thanks

**Comment by hlavki** [comment]
This looks like problem with LDAP connection. Synchronizer needs to be connected to existing LDAP. Can you send me full log and docker-compose.yml?

**Comment by rsaple** [comment]
Have a samba server(ldap) sitting on the domain agni.loc which I can access and query(ldapsearch) successfully. Does the ldap domain and the gsuite domain need to be the same for this to work? 

```

services:
  identity:
    image: hlavki/g-suite-identity-sync
    ports:
      - 8181:8181
      - 8101:8101
    environment:
      - SLAPD_BIND_DN=cn=admin admin,cn=Users,dc=agni,dc=loc
      - SLAPD_BASE_DN=dc=agni,dc=loc
      - SLAPD_PASSWORD=*****
      - GSUITE_DOMAIN=agniinfosystems.co.in
      - GSUITE_SERVICE_ACCOUNT_EMAIL=gsuite-services@prefab-pride-207206.iam.gserviceaccount.com
      - GSUITE_SERVICE_ACCOUNT_SUBJECT=rahul@agniinfosystems.co.in
      - GSUITE_CLIENT_ID=234295305813-1fvct7qa7jafgiv3k83h9507nuouepj0.apps.googleusercontent.com
      - GSUITE_CLIENT_SECRET=*Oauth Client secret*
    depends_on:
      - ldap
    volumes:
      - identity-config:/opt/karaf/etc/identity

ldap:
    image: osixia/openldap
    ports:
      - "389:389"
    environment:
      LDAP_LOG_LEVEL: "256"
      LDAP_ORGANISATION: "Agni Info ltd."
      LDAP_DOMAIN: "agni.loc"
      LDAP_ADMIN_PASSWORD: "*******"
      LDAP_CONFIG_PASSWORD: "********"
    volumes:
      - ldap-data:/var/lib/ldap
      - ldap-config:/etc/ldap/slapd.d
```

And here's the full log trace

[log_trace.txt](https://github.com/hlavki/g-suite-identity-sync/files/2105069/log_trace.txt)
